# Generated by Django 3.0.4 on 2020-10-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific',
            name='title',
            field=models.CharField(default='Experience', max_length=50),
        ),
    ]
