# Generated by Django 3.0.4 on 2020-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0002_specific_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
