# Generated by Django 3.1.2 on 2020-10-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0003_specific_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific',
            name='description',
            field=models.CharField(default='This is what I did', max_length=2000),
        ),
    ]
