# Generated by Django 3.0.4 on 2020-10-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0004_auto_20200929_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='user',
        ),
        migrations.AddField(
            model_name='experiences',
            name='userProfile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='collegeHub.UserProfile'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='Section', max_length=30),
        ),
        migrations.AlterField(
            model_name='specific',
            name='bullet_section',
            field=models.CharField(default='Bullet, points, are, great', max_length=200),
        ),
        migrations.AlterField(
            model_name='specific',
            name='description',
            field=models.CharField(default='This is what did', max_length=2000),
        ),
        migrations.AlterField(
            model_name='specific',
            name='image',
            field=models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='specific',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific', to='collegeHub.Section'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='media/')),
                ('location', models.CharField(default='NA', max_length=50, null=True)),
                ('certification_name', models.CharField(default='NA', max_length=50)),
                ('description', models.CharField(default='NA', max_length=280)),
                ('month', models.IntegerField(default='01', max_length=2)),
                ('year', models.IntegerField(default='9999', max_length=4)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='collegeHub.UserProfile')),
            ],
        ),
    ]
