# Generated by Django 3.0.4 on 2020-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0004_auto_20201017_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
