# Generated by Django 3.0.4 on 2020-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0005_auto_20201011_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='month',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(default='9999', max_length=4),
        ),
    ]
