# Generated by Django 3.0.6 on 2020-10-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0006_auto_20201018_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific', to='collegeHub.Section'),
        ),
    ]
