# Generated by Django 3.0.4 on 2020-10-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0007_auto_20201018_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specific',
            name='title',
        ),
        migrations.AddField(
            model_name='specific',
            name='company',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specific',
            name='position',
            field=models.CharField(default='', max_length=50),
        ),
    ]
