# Generated by Django 3.0.4 on 2020-10-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0008_auto_20201019_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='location',
            new_name='institution',
        ),
    ]
