# Generated by Django 3.1.2 on 2020-10-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0008_auto_20201019_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the Event')),
                ('start_time', models.TimeField(help_text='Start time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Finishing time')),
                ('notes', models.TextField(blank=True, help_text='Event description', null=True, verbose_name='Event description')),
            ],
        ),
    ]
