# Generated by Django 3.0.4 on 2020-10-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0012_auto_20201026_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='specific',
            name='image',
            field=models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='images/'),
        ),
    ]
