# Generated by Django 3.1.2 on 2020-10-27 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0013_auto_20201026_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certification_name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='NA', max_length=280),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='collegeHub.userprofile'),
        ),
        migrations.AlterField(
            model_name='specific',
            name='image',
            field=models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='media/'),
        ),
    ]
