# Generated by Django 3.1.2 on 2020-10-27 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0009_individualscheduler'),
        ('collegeHub', '0015_auto_20201027_1556'),
    ]

    operations = [
    ]
