# Generated by Django 3.1.2 on 2020-10-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0016_auto_20201030_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
    ]
