# Generated by Django 3.1.2 on 2020-11-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0017_auto_20201030_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='Section', max_length=30),
        ),
    ]
