# Generated by Django 3.1.3 on 2020-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0018_auto_20201103_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Event description', null=True, verbose_name='Event description')),
            ],
            options={
                'verbose_name': 'IndividualScheduling',
                'verbose_name_plural': 'IndividualScheduling',
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
