# Generated by Django 3.1.2 on 2020-11-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0019_auto_20201103_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='This is what I did', max_length=2000)),
                ('image', models.ImageField(blank=True, default='media/right-arrow.png', null=True, upload_to='media/')),
                ('month', models.CharField(blank=True, default='01', max_length=2, null=True)),
                ('year', models.CharField(default='9999', max_length=4)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='collegeHub.userprofile')),
            ],
        ),
    ]
