# Generated by Django 3.1.3 on 2020-11-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0019_auto_20201103_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
