# Generated by Django 3.1.2 on 2020-11-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0020_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
