# Generated by Django 3.1.2 on 2020-11-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0021_auto_20201105_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='month',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
