# Generated by Django 3.1.3 on 2020-11-03 23:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0021_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscheduler',
            name='notes',
        ),
        migrations.AddField(
            model_name='individualscheduler',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualscheduler',
            name='start_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
