# Generated by Django 3.1.3 on 2020-11-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0022_auto_20201104_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualscheduler',
            name='title',
        ),
        migrations.AddField(
            model_name='individualscheduler',
            name='notes',
            field=models.TextField(blank=True, help_text='Event description', null=True, verbose_name='Event description'),
        ),
        migrations.AlterField(
            model_name='individualscheduler',
            name='start_time',
            field=models.TimeField(help_text='Starting time', verbose_name='Starting time'),
        ),
    ]
