# Generated by Django 3.1.3 on 2020-11-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0023_auto_20201104_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualscheduler',
            old_name='notes',
            new_name='title',
        ),
    ]
