# Generated by Django 3.1.2 on 2020-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0024_auto_20201116_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio_html',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
