# Generated by Django 3.1.3 on 2020-11-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0025_auto_20201104_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='day',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling', to='collegeHub.userprofile'),
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeHub.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeHub.user')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
