# Generated by Django 3.1.2 on 2020-11-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0025_auto_20201116_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
