# Generated by Django 3.1.2 on 2020-11-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0026_auto_20201116_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
