# Generated by Django 3.1.3 on 2020-11-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0026_auto_20201104_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_date',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='notes',
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
