# Generated by Django 3.1.2 on 2020-11-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0027_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
