# Generated by Django 3.1.2 on 2020-11-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0028_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='template_number',
            field=models.IntegerField(default=0),
        ),
    ]
