# Generated by Django 3.1.2 on 2020-11-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0029_userprofile_template_number'),
        ('collegeHub', '0028_post_profile'),
    ]

    operations = [
    ]
