# Generated by Django 3.1.2 on 2020-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0030_merge_20201126_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
