# Generated by Django 3.1.2 on 2020-12-07 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0034_auto_20201205_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_group',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
