# Generated by Django 3.1.2 on 2020-12-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0036_auto_20201207_0705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
