# Generated by Django 3.1.2 on 2020-12-08 01:46

import collegeHub.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0037_delete_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/BlueHead.jpg', null=True, upload_to='images/', validators=[collegeHub.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[collegeHub.validators.validate_pdf]),
        ),
    ]
