# Generated by Django 3.1.2 on 2020-12-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0037_delete_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-year']},
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.DateTimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual Notes')),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='group_events', to='collegeHub.UserProfile')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
