# Generated by Django 3.1.2 on 2020-12-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeHub', '0038_auto_20201207_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupevent',
            name='user',
        ),
        migrations.AddField(
            model_name='groupevent',
            name='confirmed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='confirmed_users', to='collegeHub.UserProfile'),
        ),
        migrations.AddField(
            model_name='groupevent',
            name='pending_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='pending_users', to='collegeHub.UserProfile'),
        ),
    ]
